### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by fjsj** [karan/joe#14]
```
fjsj$ sudo pip install joe
Collecting joe
  Downloading joe-0.0.3.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-gONlfD/joe/setup.py", line 10, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-gONlfD/joe/setup.py", line 10, in <module>

        long_description=open('README.md').read(),

    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gONlfD/joe
```

**Comment by karan** [comment]
Fixed in v0.0.4.

1ad94ff4fccaf2ba58ad69edae12234e2c70cfb7
458e2df64835a3e464a3a20db1aac809edf7b1ef
b505e668fbf60c7c5376fc5d4ff8940ffbf289be
f57c280dad5aa9dfe3ba472bb3090811ebcaaff1
