### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by dontdieych** [karan/joe#38]
Arch Linux

```
$ pacman -Q python
python 3.4.2-2
$ pacman -Q python-pip
python-pip 6.0.8-1
$ type joe
joe is /home/dontdieych/.local/bin/joe
$ which joe
/home/dontdieych/.local/bin/joe
$ joe
Traceback (most recent call last):
  File "/home/dontdieych/.local/bin/joe", line 9, in <module>
    load_entry_point('joe==0.0.5', 'console_scripts', 'joe')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dontdieych/.local/lib/python3.4/site-packages/joe/joe.py", line 59
    print ', '.join(GITIGNORE)
             ^
SyntaxError: invalid syntax
$
```

**Comment by karan** [comment]
How did you install it?

Py3 compatibility was recently merged in `master`, and hasn't been put up on pypi yet. Try [installing from source](https://github.com/karan/joe#option-3-from-source) and it should work.

**Comment by dontdieych** [comment]
Thanks. It's working.

PR: should change git@github.com:karan/joe.git -> https://github.com/karan/joe on README. It's private only address.
