### ISSUE TITLE
Joe is not working when installed through brew

### ISSUE THREAD

**Issue by robertd** [karan/joe#71]
``` bash
➜  ~ brew install karan/karan/gitignore
...
➜  ~ joe
Traceback (most recent call last):
  File "/usr/local/Cellar/gitignore/0.0.7/libexec/bin/joe", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: gitdb>=0.6.4
```

**Comment by karan** [comment]
Uhh ok I know why this is happening but I don't have the time to fix it this week. You can install it by source or pypi though!

**Comment by sobolevn** [comment]
The same is when trying to update to the new version. 

```
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/joe-0.0.6-py2.7.egg-info/dependency_links.txt'
```

**Comment by wcravens** [comment]
@karan Could you provide a description of the fix so that someone else could pick it up?  Or is it one of those 'takes as long to describe as it does to fix' problems?

**Comment by karan** [comment]
I've rewritten joe in Go now and distribution is through binaries. Give that a shot: https://github.com/karan/joe/releases/tag/1.0.0

**Comment by robertd** [comment]
will this be available through brew?

**Comment by karan** [comment]
Not for a little while at least.
